services:
  backend:
    build: ./backend
    image: meethub-backend:web
    container_name: meethub-backend
    ports:
      - "8088:8088"
    env_file:
      - ./backend/.env
    volumes:
      - ./logs:/app/logs
    networks:
      - meethub_network
    environment:
      TZ: Asia/Seoul

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"

    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - certbot-webroot:/var/www/certbot
    depends_on:
      - certbot
      - backend

    networks:
      - meethub_network
      - jenkins_network
      - portainer_network
      - monitoring_network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - certbot-webroot:/var/www/certbot
    entrypoint: /bin/sh -c
    command: >
      "trap exit TERM;
       while :; do sleep 6h & wait $${!}; certbot renew --webroot -w /var/www/certbot --quiet; done"
    user: "0:0"
    networks:
      - meethub_network

networks:
  meethub_network:
    name: meethub_network
    driver: bridge
  jenkins_network:
    driver: bridge
    external: true
  portainer_network:
    driver: bridge
    external: true
  monitoring_network:
    driver: bridge
    external: true
volumes:
  certbot-webroot:
    name: certbot-webroot
