server.servlet.context-path=/api
server.port=8088
spring.application.name=backend
# JWT Settings
jwt.secret=${JWT_SECRET}
jwt.access-token-validity=300000
jwt.refresh-token-validity=604800000
# MySQL
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.timeout=2000ms
spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=0
spring.data.redis.repositories.enabled=false
# JPA
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO}
spring.jpa.show-sql=${JPA_SHOW_SQL}
spring.jpa.properties.hibernate.format_sql=${JPA_FORMAT_SQL}
# Swagger
springdoc.swagger-ui.enabled=${app.swagger-enabled}
springdoc.swagger-ui.path=/docs
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.api-docs.enabled=${app.swagger-enabled}
springdoc.api-docs.path=/api-docs
# App
app.cors-origins=${CORS_ORIGINS:http://localhost:3000}
app.swagger-enabled=${SWAGGER_ENABLED:true}
app.max-folder-depth=${MAX_FOLDER_DEPTH:7}
# LiveKit
livekit.url=${LIVEKIT_URL}
livekit.api-key=${LIVEKIT_API_KEY}
livekit.api-secret=${LIVEKIT_API_SECRET}
# Python Agent
agent.name=${AGENT_NAME}
#Timezone
spring.datasource.hikari.connection-init-sql=SET time_zone = '+09:00'

management.endpoints.web.exposure.include=prometheus,health,info
management.endpoints.web.base-path: /actuator
management.endpoint.health.show-details=always
management.endpoint.prometheus.enabled=true

management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.tags.application=${spring.application.name}


logging.file.name=/app/logs/application.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} %5level %d{PID} --- [%15.15thread] %-40.40logger{39} : %msg%n
logging.logback.rollingpolicy.max-file-size=100MB
logging.logback.rollingpolicy.max-history=30
logging.logback.rollingpolicy.total-size-cap=3GB
logging.logback.rollingpolicy.file-name-pattern=./monitoring/logs/application.%d{yyyy-MM-dd}.%i.log
logging.level.root=INFO
logging.level.com.your.package=DEBUG
logging.level.org.springframework.security=DEBUG